### PR TITLE
Humble Docker Compose beginnings for THREDDS container

### PR DESCRIPTION
**Pull request by isuftin**
Ripped the Docker compose configuration out from the Unidata THREDDS Docker PR and brought it into here to begin with

### CODE REVIEW

**Comment by isuftin** [comment]
Implements https://github.com/USGS-CMG/data-life-cycle-cloud/issues/7

**Comment by rsignell-usgs** [comment]
@isuftin would you like me to review something in particular?

**Comment by isuftin** [comment]
@rsignell-usgs Not unless you want to. I'm just going to be making a lot of PRs as I develop this out and this one may still need a few additions

**Comment by rsignell-usgs** [comment]
So would you like me to pro-forma merge or are you going to merge your own PRs?

**Comment by isuftin** [comment]
@rsignell-usgs I'm fine with merging my own unless you'd like to?

**Comment by rsignell-usgs** [comment]
I'm fine with you merging your own.   Just let me know if would like input or review.

**Comment by isuftin** [comment]
@rsignell-usgs Could you give me write rights on this repo? I'm actually not able to merge myself

**Comment by rsignell-usgs** [comment]
@isuftin okay you should be good now.

**Pull request merged**
